default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: to-cr_development

test:
  <<: *default
  database: to-cr_test

production:
  <<: *default
  database: to-cr_production
  username: to-cr
  password: <%= ENV['TO-CR_DATABASE_PASSWORD'] %>
